#!/usr/bin/env python

import os
import sys

import torch
from diffusers import FluxPipeline

os.makedirs("diffusers-cache", exist_ok=True)

token = sys.argv[1] if len(sys.argv) > 1 else None

FluxPipeline.from_pretrained(
    "black-forest-labs/FLUX.1-dev",
    torch_dtype=torch.bfloat16,
    cache_dir="diffusers-cache",
    use_auth_token=token,
)
